/* Generated By:JavaCC: Do not edit this line. ZParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int AT = 2;
  /** RegularExpression Id. */
  int AMP = 3;
  /** RegularExpression Id. */
  int DOLLAR = 4;
  /** RegularExpression Id. */
  int EQUALS = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ID>",
    "<AT>",
    "<AMP>",
    "<DOLLAR>",
    "<EQUALS>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
